### ISSUE TITLE
Website Updated Popup

### ISSUE THREAD

**Issue by Hardik-S** [mwiraszka/LondonChessClub#152]
![image](https://github.com/mwiraszka/LondonChessClub/assets/24942660/39a9bad8-6446-403d-93b6-1ab3f47f2a73)

Pop-up in above image appears twice. Given there is no other action possible, ideal solutions in order would be 

1) Only push updates to live at 4 am, no need for interference. 
2) If there does need to be a refresh, just refresh rather than make me click a button. 
3) Enable me to not refresh the page immediately, and save/ copy my work.

**Comment by mwiraszka** [comment]
Resolved. When a new website version becomes available, a pop up will no longer appear, forcing the user to refresh the page. Instead, a simple notification message will appear in the app footer.
