### ISSUE TITLE
News Articles Display 4/ 5

### ISSUE THREAD

**Issue by Hardik-S** [mwiraszka/LondonChessClub#153]
Doesn't correctly decide how many articles to display. Should be 4. The next row shouldn't have just 1 article.

![image](https://github.com/mwiraszka/LondonChessClub/assets/24942660/88130616-79bf-4c7b-994b-7a3b3f9024d4)

**Comment by mwiraszka** [comment]
Working as expected. Article cards have a minimum width, so when there isn't enough space for 5 cards on a row, the surplus is moved to the next row and horizontally centred.
